### ISSUE TITLE
List of values preview

### ISSUE THREAD

**Issue by maksutovaynur** [bendalab/NixView#82]
Dear Jan,
when property has a list of values, the preview if wrong: it doesn't display commas between separate values. Could you please look on screenshot   https://www.dropbox.com/s/zuxclgrwj2v1scn/Screenshot%20from%202016-08-02%2017-46-40.png?dl=0     ?

**Comment by jgrewe** [comment]
this should be solved with the latest commits. Please let me know, if you have further suggestions/

**Comment by maksutovaynur** [comment]
Thanks a lot!


>Вторник, 23 августа 2016, 21:22 +02:00 от Jan Grewe <notifications@github.com>:
>
>this should be solved with the latest commits. Please let me know, if you have further suggestions/
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Aynur Maksutov
