### ISSUE TITLE
Help with building NixView on Ubuntu with Anaconda installed

### ISSUE THREAD

**Issue by dEvasEnApati** [bendalab/NixView#86]
Hi Jan

I tried to build the current version of NixView on my Ubuntu 1604 machine with Anaconda installed in it. It built without error but I think there is a linking problem. Here is the error message when I try to run nix-view:

	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./nix-view)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./nix-view)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/lib/libnix.so.1)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/lib/libnix.so.1)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.58.0)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicui18n.so.55)
	./nix-view: /home/ajay/Installations/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.55)

Could you please help me build this?

Sincerely
Ajay

**Comment by jgrewe** [comment]
Hi Ajay,

never seen this before, must be related to the libs anaconda installs. I found this issue describing a similar [problem](https://github.com/aseprite/aseprite/issues/1281). 
I hope this helps. Did you install nix from source or via apt?

**Comment by jgrewe** [comment]
Even better: apparently installing libgcc with conda may [help](https://github.com/dmlc/xgboost/issues/1043). Let me know if it worked for you.

**Comment by dEvasEnApati** [comment]
Hi Jan

I installed libgcc with conda and now it builds fine. It works fine as well.

Thanks a lot!

Sincerely
Ajay

**Comment by jgrewe** [comment]
That's very good to know! Thanks.
